name: ResourceWorld
version: 1.4.7
main: me.nik.resourceworld.ResourceWorld
api-version: 1.13
load: POSTWORLD
authors: [Nik]
description: Unlimited resources!
commands:
  resource:
    description: Unlimited resources!
    usage: /<command>
    aliases:
      - rw
      - resourceworld
permissions:
  rw.tp:
    description: Randomly Teleport To The Resource World!
    default: true
  rw.tp.nether:
    description: Randomly Teleport To The Nether Resource World!
  rw.tp.end:
    description: Randomly Teleport To The End Resource World!
  rw.tp.*:
    description: Access To Teleport To All The Resource Worlds!
    default: op
    children:
      rw.tp: true
      rw.tp.nether: true
      rw.tp.end: true
  rw.admin:
    description: Access to the Resource World admin commands!
    default: op
